### ISSUE TITLE
Version is incorrect with ansible-galaxy

### ISSUE THREAD

**Issue by btravouillon** [jsl6ul/server_settings#36]
With what seems to be v0.3.9, the version is shown as 1.0.0 in ansible-galaxy.

My `requirements.yml`:
```
collections:
  - name: https://github.com/jsl6ul/server_settings.git
    type: git
    version: v0.3.9
```

Output of `ansible-galaxy`:
```
$ ansible-galaxy collection list|grep server_settings
jsl6ul.server_settings                   1.0.0
```

https://github.com/jsl6ul/server_settings/blob/2b1d9cafe91ac0d4d57cb68506079826bed68dff/galaxy.yml#L10 might need an update before next release.
